### ISSUE TITLE
Task from all running containers seams to get registered

### ISSUE THREAD

**Issue by alesak** [netresearch/ofelia#44]
Task from all running containers seams to get registered even when 

`ofelia daemon -f label=com.docker.compose.project=${COMPOSE_PROJECT_NAME}`

is used

**Comment by TheDevMinerTV** [comment]
Yep, I've noticed the same issue. When I get time I'll look into it. thank you for reporting this!

**Comment by TheDevMinerTV** [comment]
The fix is released in v0.6.5: https://github.com/netresearch/ofelia/releases/tag/v0.6.5
